on:
  push:
    branches: 
      - main
      - master

name: Render & Publish Site

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.2.112

      - name: Render Site
        uses: quarto-dev/quarto-actions/render@v2

      - name: No Jekyll
        run: |
          touch _site/.nojekyll

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: _site
          single-commit: true